name: food_market_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.0.0
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.0
  shared_preferences: ^2.2.3
  supercharged: ^2.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
